import type { Pokemon, Move, Location, Spawn, Item, Request } from '@/types/pokemon';

// Seed data with 20 Pokémon from Legends: Arceus
export const seedPokemon: Pokemon[] = [
  {
    id: 'rowlet',
    dex_no: 1,
    name_ar: 'رولِت',
    name_en: 'Rowlet',
    types: ['grass', 'flying'],
    tags: ['starter'],
    stats: { hp: 68, atk: 55, def: 55, spa: 50, spd: 50, spe: 42 },
    description_ar: 'بوكيمون البومة العشبية. يُطلق ريشاً حاداً على أعدائه.',
    description_en: 'The Grass Quill Pokémon. It launches sharp feathers at enemies.',
    evolutions: [{ to_id: 'dartrix', conditions_ar: 'المستوى 17', conditions_en: 'Level 17' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/722.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/722.png' },
    learnset: [],
    spawn_refs: ['spawn-rowlet-1'],
  },
  {
    id: 'cyndaquil',
    dex_no: 4,
    name_ar: 'سينداكويل',
    name_en: 'Cyndaquil',
    types: ['fire'],
    tags: ['starter'],
    stats: { hp: 39, atk: 52, def: 43, spa: 60, spd: 50, spe: 65 },
    description_ar: 'بوكيمون الفأر الناري. يُشعل ألسنة اللهب من ظهره عند الخطر.',
    description_en: 'The Fire Mouse Pokémon. It ignites flames from its back when in danger.',
    evolutions: [{ to_id: 'quilava', conditions_ar: 'المستوى 14', conditions_en: 'Level 14' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/155.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/155.png' },
    learnset: [],
    spawn_refs: [],
  },
  {
    id: 'oshawott',
    dex_no: 7,
    name_ar: 'أوشاوُت',
    name_en: 'Oshawott',
    types: ['water'],
    tags: ['starter'],
    stats: { hp: 55, atk: 55, def: 45, spa: 63, spd: 45, spe: 45 },
    description_ar: 'بوكيمون قضاعة البحر. يستخدم الصدفة على بطنه كسلاح.',
    description_en: 'The Sea Otter Pokémon. It uses the scalchop on its belly as a weapon.',
    evolutions: [{ to_id: 'dewott', conditions_ar: 'المستوى 17', conditions_en: 'Level 17' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/501.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/501.png' },
    learnset: [],
    spawn_refs: [],
  },
  {
    id: 'bidoof',
    dex_no: 13,
    name_ar: 'بيدووف',
    name_en: 'Bidoof',
    types: ['normal'],
    tags: [],
    stats: { hp: 59, atk: 45, def: 40, spa: 35, spd: 40, spe: 31 },
    description_ar: 'بوكيمون السمّور. يقضم الأشجار والصخور بأسنانه القوية.',
    description_en: 'The Plump Mouse Pokémon. It gnaws on trees and rocks with its strong teeth.',
    evolutions: [{ to_id: 'bibarel', conditions_ar: 'المستوى 15', conditions_en: 'Level 15' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/399.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/399.png' },
    learnset: [],
    spawn_refs: ['spawn-bidoof-1'],
  },
  {
    id: 'starly',
    dex_no: 15,
    name_ar: 'ستارلي',
    name_en: 'Starly',
    types: ['normal', 'flying'],
    tags: [],
    stats: { hp: 40, atk: 55, def: 30, spa: 30, spd: 30, spe: 60 },
    description_ar: 'بوكيمون الزرزور. يطير في أسراب كبيرة.',
    description_en: 'The Starling Pokémon. It flies in large flocks.',
    evolutions: [{ to_id: 'staravia', conditions_ar: 'المستوى 14', conditions_en: 'Level 14' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/396.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/396.png' },
    learnset: [],
    spawn_refs: ['spawn-starly-1'],
  },
  {
    id: 'shinx',
    dex_no: 17,
    name_ar: 'شينكس',
    name_en: 'Shinx',
    types: ['electric'],
    tags: [],
    stats: { hp: 45, atk: 65, def: 34, spa: 40, spd: 34, spe: 45 },
    description_ar: 'بوكيمون الومضة. يولّد الكهرباء عند تقلص عضلاته.',
    description_en: 'The Flash Pokémon. It generates electricity when its muscles contract.',
    evolutions: [{ to_id: 'luxio', conditions_ar: 'المستوى 15', conditions_en: 'Level 15' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/403.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/403.png' },
    learnset: [],
    spawn_refs: ['spawn-shinx-1'],
  },
  {
    id: 'ponyta',
    dex_no: 22,
    name_ar: 'بونيتا',
    name_en: 'Ponyta',
    types: ['fire'],
    tags: [],
    stats: { hp: 50, atk: 85, def: 55, spa: 65, spd: 65, spe: 90 },
    description_ar: 'بوكيمون حصان النار. عُرفه ولهيب ذيله يشتعلان بشدة.',
    description_en: 'The Fire Horse Pokémon. Its mane and tail blaze fiercely.',
    evolutions: [{ to_id: 'rapidash', conditions_ar: 'المستوى 40', conditions_en: 'Level 40' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png' },
    learnset: [],
    spawn_refs: ['spawn-ponyta-1'],
  },
  {
    id: 'eevee',
    dex_no: 26,
    name_ar: 'إيفي',
    name_en: 'Eevee',
    types: ['normal'],
    tags: [],
    stats: { hp: 55, atk: 55, def: 50, spa: 45, spd: 65, spe: 55 },
    description_ar: 'بوكيمون التطور. يستطيع التطور لأشكال عديدة.',
    description_en: 'The Evolution Pokémon. It can evolve into many different forms.',
    evolutions: [
      { to_id: 'vaporeon', conditions_ar: 'حجر الماء', conditions_en: 'Water Stone' },
      { to_id: 'jolteon', conditions_ar: 'حجر الرعد', conditions_en: 'Thunder Stone' },
      { to_id: 'flareon', conditions_ar: 'حجر النار', conditions_en: 'Fire Stone' },
    ],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png' },
    learnset: [],
    spawn_refs: ['spawn-eevee-1'],
  },
  {
    id: 'pikachu',
    dex_no: 34,
    name_ar: 'بيكاتشو',
    name_en: 'Pikachu',
    types: ['electric'],
    tags: [],
    stats: { hp: 35, atk: 55, def: 40, spa: 50, spd: 50, spe: 90 },
    description_ar: 'بوكيمون الفأر. يخزّن الكهرباء في خديه.',
    description_en: 'The Mouse Pokémon. It stores electricity in its cheeks.',
    evolutions: [{ to_id: 'raichu', conditions_ar: 'حجر الرعد', conditions_en: 'Thunder Stone' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png' },
    learnset: [],
    spawn_refs: ['spawn-pikachu-1'],
  },
  {
    id: 'gastly',
    dex_no: 41,
    name_ar: 'غاستلي',
    name_en: 'Gastly',
    types: ['ghost', 'poison'],
    tags: [],
    stats: { hp: 30, atk: 35, def: 30, spa: 100, spd: 35, spe: 80 },
    description_ar: 'بوكيمون الغاز. جسمه مكوّن من غاز سام.',
    description_en: 'The Gas Pokémon. Its body is made of poisonous gas.',
    evolutions: [{ to_id: 'haunter', conditions_ar: 'المستوى 25', conditions_en: 'Level 25' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png' },
    learnset: [],
    spawn_refs: ['spawn-gastly-1'],
  },
  {
    id: 'abra',
    dex_no: 44,
    name_ar: 'أبرا',
    name_en: 'Abra',
    types: ['psychic'],
    tags: [],
    stats: { hp: 25, atk: 20, def: 15, spa: 105, spd: 55, spe: 90 },
    description_ar: 'بوكيمون النفسي. ينام 18 ساعة يومياً ويستشعر الخطر نائماً.',
    description_en: 'The Psi Pokémon. It sleeps 18 hours a day and senses danger while sleeping.',
    evolutions: [{ to_id: 'kadabra', conditions_ar: 'المستوى 16', conditions_en: 'Level 16' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png' },
    learnset: [],
    spawn_refs: ['spawn-abra-1'],
  },
  {
    id: 'machop',
    dex_no: 47,
    name_ar: 'ماشوب',
    name_en: 'Machop',
    types: ['fighting'],
    tags: [],
    stats: { hp: 70, atk: 80, def: 50, spa: 35, spd: 35, spe: 35 },
    description_ar: 'بوكيمون القوة الخارقة. يتدرب برفع الصخور الثقيلة.',
    description_en: 'The Superpower Pokémon. It trains by lifting heavy boulders.',
    evolutions: [{ to_id: 'machoke', conditions_ar: 'المستوى 28', conditions_en: 'Level 28' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png' },
    learnset: [],
    spawn_refs: ['spawn-machop-1'],
  },
  {
    id: 'geodude',
    dex_no: 50,
    name_ar: 'جيودود',
    name_en: 'Geodude',
    types: ['rock', 'ground'],
    tags: [],
    stats: { hp: 40, atk: 80, def: 100, spa: 30, spd: 30, spe: 20 },
    description_ar: 'بوكيمون الصخرة. يتدحرج من المنحدرات بحثاً عن الطعام.',
    description_en: 'The Rock Pokémon. It rolls down slopes looking for food.',
    evolutions: [{ to_id: 'graveler', conditions_ar: 'المستوى 25', conditions_en: 'Level 25' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png' },
    learnset: [],
    spawn_refs: ['spawn-geodude-1'],
  },
  {
    id: 'drifloon',
    dex_no: 55,
    name_ar: 'دريفلون',
    name_en: 'Drifloon',
    types: ['ghost', 'flying'],
    tags: [],
    stats: { hp: 90, atk: 50, def: 34, spa: 60, spd: 44, spe: 70 },
    description_ar: 'بوكيمون البالون. يحاول أخذ الأطفال إلى عالم الأرواح.',
    description_en: 'The Balloon Pokémon. It tries to take children to the spirit world.',
    evolutions: [{ to_id: 'drifblim', conditions_ar: 'المستوى 28', conditions_en: 'Level 28' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/425.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/425.png' },
    learnset: [],
    spawn_refs: ['spawn-drifloon-1'],
  },
  {
    id: 'hisuian-growlithe',
    dex_no: 58,
    name_ar: 'غراوليث هيسوي',
    name_en: 'Hisuian Growlithe',
    types: ['fire', 'rock'],
    tags: ['hisuian'],
    stats: { hp: 60, atk: 75, def: 45, spa: 65, spd: 50, spe: 55 },
    description_ar: 'بوكيمون الجرو الحارس. نسخة هيسوي ذات فراء صخري.',
    description_en: 'The Scout Pokémon. Hisuian form with rocky fur.',
    evolutions: [{ to_id: 'hisuian-arcanine', conditions_ar: 'حجر النار', conditions_en: 'Fire Stone' }],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10229.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10229.png' },
    learnset: [],
    spawn_refs: ['spawn-hgrowlithe-1'],
  },
  {
    id: 'kleavor',
    dex_no: 65,
    name_ar: 'كليفور',
    name_en: 'Kleavor',
    types: ['bug', 'rock'],
    tags: ['noble', 'hisuian'],
    stats: { hp: 70, atk: 135, def: 95, spa: 45, spd: 70, spe: 85 },
    description_ar: 'بوكيمون الفأس. يُمكنه تقطيع الأشجار بذراعيه الحادتين.',
    description_en: 'The Axe Pokémon. It can fell trees with its sharp arms.',
    evolutions: [],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/900.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/900.png' },
    learnset: [],
    spawn_refs: ['spawn-kleavor-1'],
  },
  {
    id: 'alpha-snorlax',
    dex_no: 95,
    name_ar: 'سنورلاكس ألفا',
    name_en: 'Alpha Snorlax',
    types: ['normal'],
    tags: ['alpha'],
    stats: { hp: 160, atk: 110, def: 65, spa: 65, spd: 110, spe: 30 },
    description_ar: 'نسخة ألفا ضخمة من سنورلاكس. عيناه حمراوان متوهجتان.',
    description_en: 'A massive Alpha form of Snorlax. It has glowing red eyes.',
    evolutions: [],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png' },
    learnset: [],
    spawn_refs: ['spawn-alpha-snorlax-1'],
  },
  {
    id: 'dialga-origin',
    dex_no: 230,
    name_ar: 'ديالجا الأصلي',
    name_en: 'Origin Dialga',
    types: ['steel', 'dragon'],
    tags: ['legendary'],
    stats: { hp: 100, atk: 100, def: 120, spa: 150, spd: 120, spe: 90 },
    description_ar: 'شكل ديالجا الأصلي. يتحكم بالزمن ذاته.',
    description_en: 'Origin form of Dialga. It controls time itself.',
    evolutions: [],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10249.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10249.png' },
    learnset: [],
    spawn_refs: ['spawn-dialga-1'],
  },
  {
    id: 'palkia-origin',
    dex_no: 231,
    name_ar: 'بالكيا الأصلي',
    name_en: 'Origin Palkia',
    types: ['water', 'dragon'],
    tags: ['legendary'],
    stats: { hp: 90, atk: 100, def: 100, spa: 150, spd: 120, spe: 120 },
    description_ar: 'شكل بالكيا الأصلي. يتحكم بالمكان ذاته.',
    description_en: 'Origin form of Palkia. It controls space itself.',
    evolutions: [],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10250.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10250.png' },
    learnset: [],
    spawn_refs: ['spawn-palkia-1'],
  },
  {
    id: 'arceus',
    dex_no: 238,
    name_ar: 'أركيوس',
    name_en: 'Arceus',
    types: ['normal'],
    tags: ['mythical'],
    stats: { hp: 120, atk: 120, def: 120, spa: 120, spd: 120, spe: 120 },
    description_ar: 'يُقال إنه خلق كل شيء. إله البوكيمون.',
    description_en: 'It is said to have created everything. The god of Pokémon.',
    evolutions: [],
    images: { thumb: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493.png', artwork: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/493.png' },
    learnset: [],
    spawn_refs: ['spawn-arceus-1'],
  },
];

export const seedLocations: Location[] = [
  {
    id: 'obsidian-fieldlands',
    name_ar: 'أراضي السبج',
    name_en: 'Obsidian Fieldlands',
    region: 'hisui',
    description_ar: 'منطقة عشبية واسعة مليئة بالبوكيمونات المتنوعة.',
    description_en: 'A vast grassy area filled with diverse Pokémon.',
    subareas: [
      { name_ar: 'ساحة آسباراتيون', name_en: 'Aspiration Hill' },
      { name_ar: 'غابة خشب القلب', name_en: 'Heartwood' },
      { name_ar: 'بحيرة الحق', name_en: 'Lake Verity' },
    ],
  },
  {
    id: 'crimson-mirelands',
    name_ar: 'مستنقعات القرمز',
    name_en: 'Crimson Mirelands',
    region: 'hisui',
    description_ar: 'أراضٍ رطبة مليئة بالمستنقعات والبوكيمونات المائية.',
    description_en: 'Wetlands full of swamps and Water-type Pokémon.',
    subareas: [
      { name_ar: 'غابة السحابة', name_en: 'Cloudpool Ridge' },
      { name_ar: 'معسكر البوغ', name_en: 'Bogbound Camp' },
    ],
  },
  {
    id: 'cobalt-coastlands',
    name_ar: 'سواحل الكوبالت',
    name_en: 'Cobalt Coastlands',
    region: 'hisui',
    description_ar: 'سواحل وشواطئ مع بوكيمونات مائية وطائرة.',
    description_en: 'Coasts and beaches with Water and Flying Pokémon.',
    subareas: [
      { name_ar: 'شاطئ جينكو', name_en: 'Ginkgo Landing' },
      { name_ar: 'جزيرة الطوفان', name_en: 'Firespit Island' },
    ],
  },
  {
    id: 'coronet-highlands',
    name_ar: 'مرتفعات كورونيت',
    name_en: 'Coronet Highlands',
    region: 'hisui',
    description_ar: 'جبال شاهقة ومنطقة أثرية مهمة.',
    description_en: 'Towering mountains and an important archaeological area.',
    subareas: [
      { name_ar: 'معبد سينجو', name_en: 'Sinnoh Temple' },
      { name_ar: 'قمة كورونيت', name_en: 'Coronet Peak' },
    ],
  },
  {
    id: 'alabaster-icelands',
    name_ar: 'أراضي الثلج البيضاء',
    name_en: 'Alabaster Icelands',
    region: 'hisui',
    description_ar: 'أراضٍ جليدية قاسية مع بوكيمونات الجليد.',
    description_en: 'Harsh icy lands with Ice-type Pokémon.',
    subareas: [
      { name_ar: 'بحيرة أكويتي', name_en: 'Lake Acuity' },
      { name_ar: 'أرينا الثلج', name_en: "Snowpoint Temple" },
    ],
  },
];

export const seedSpawns: Spawn[] = [
  { id: 'spawn-rowlet-1', pokemon_id: 'rowlet', location_id: 'obsidian-fieldlands', area_ar: 'ساحة آسباراتيون', area_en: 'Aspiration Hill', conditions_ar: 'نهاراً', conditions_en: 'During the day', rarity: 'uncommon', is_alpha: false },
  { id: 'spawn-bidoof-1', pokemon_id: 'bidoof', location_id: 'obsidian-fieldlands', area_ar: 'ساحة آسباراتيون', area_en: 'Aspiration Hill', conditions_ar: 'دائماً', conditions_en: 'Always', rarity: 'common', is_alpha: false },
  { id: 'spawn-starly-1', pokemon_id: 'starly', location_id: 'obsidian-fieldlands', area_ar: 'ساحة آسباراتيون', area_en: 'Aspiration Hill', conditions_ar: 'دائماً', conditions_en: 'Always', rarity: 'common', is_alpha: false },
  { id: 'spawn-shinx-1', pokemon_id: 'shinx', location_id: 'obsidian-fieldlands', area_ar: 'غابة خشب القلب', area_en: 'Heartwood', conditions_ar: 'نهاراً', conditions_en: 'During the day', rarity: 'uncommon', is_alpha: false },
  { id: 'spawn-ponyta-1', pokemon_id: 'ponyta', location_id: 'obsidian-fieldlands', area_ar: 'ساحة الحصان', area_en: 'Horseshoe Plains', conditions_ar: 'دائماً', conditions_en: 'Always', rarity: 'common', is_alpha: false },
  { id: 'spawn-eevee-1', pokemon_id: 'eevee', location_id: 'obsidian-fieldlands', area_ar: 'غابة خشب القلب', area_en: 'Heartwood', conditions_ar: 'نهاراً', conditions_en: 'During the day', rarity: 'rare', is_alpha: false },
  { id: 'spawn-pikachu-1', pokemon_id: 'pikachu', location_id: 'obsidian-fieldlands', area_ar: 'طبيعة البرق', area_en: "Nature's Pantry", conditions_ar: 'أثناء العواصف', conditions_en: 'During storms', rarity: 'rare', is_alpha: false },
  { id: 'spawn-gastly-1', pokemon_id: 'gastly', location_id: 'obsidian-fieldlands', area_ar: 'قلعة الخراب', area_en: 'Ruined Heap', conditions_ar: 'ليلاً', conditions_en: 'At night', rarity: 'uncommon', is_alpha: false },
  { id: 'spawn-abra-1', pokemon_id: 'abra', location_id: 'obsidian-fieldlands', area_ar: 'بحيرة الحق', area_en: 'Lake Verity', conditions_ar: 'دائماً', conditions_en: 'Always', rarity: 'rare', is_alpha: false },
  { id: 'spawn-machop-1', pokemon_id: 'machop', location_id: 'crimson-mirelands', area_ar: 'تلال الكهف', area_en: 'Bolderoll Slope', conditions_ar: 'دائماً', conditions_en: 'Always', rarity: 'uncommon', is_alpha: false },
  { id: 'spawn-geodude-1', pokemon_id: 'geodude', location_id: 'crimson-mirelands', area_ar: 'منحدر الصخور', area_en: 'Bolderoll Ravine', conditions_ar: 'دائماً', conditions_en: 'Always', rarity: 'common', is_alpha: false },
  { id: 'spawn-drifloon-1', pokemon_id: 'drifloon', location_id: 'obsidian-fieldlands', area_ar: 'غابة خشب القلب', area_en: 'Heartwood', conditions_ar: 'ليلاً', conditions_en: 'At night', rarity: 'uncommon', is_alpha: false },
  { id: 'spawn-hgrowlithe-1', pokemon_id: 'hisuian-growlithe', location_id: 'cobalt-coastlands', area_ar: 'جزيرة الطوفان', area_en: 'Firespit Island', conditions_ar: 'دائماً', conditions_en: 'Always', rarity: 'uncommon', is_alpha: false },
  { id: 'spawn-kleavor-1', pokemon_id: 'kleavor', location_id: 'obsidian-fieldlands', area_ar: 'ساحة الكليفور', area_en: 'Grandtree Arena', conditions_ar: 'بعد هزيمته', conditions_en: 'After defeating it', rarity: 'very_rare', is_alpha: false },
  { id: 'spawn-alpha-snorlax-1', pokemon_id: 'alpha-snorlax', location_id: 'obsidian-fieldlands', area_ar: 'بحيرة الحق', area_en: 'Lake Verity', conditions_ar: 'ثابت', conditions_en: 'Static spawn', rarity: 'very_rare', is_alpha: true },
  { id: 'spawn-dialga-1', pokemon_id: 'dialga-origin', location_id: 'coronet-highlands', area_ar: 'معبد سينجو', area_en: 'Sinnoh Temple', conditions_ar: 'بعد إكمال القصة', conditions_en: 'After completing the story', rarity: 'very_rare', is_alpha: false },
  { id: 'spawn-palkia-1', pokemon_id: 'palkia-origin', location_id: 'coronet-highlands', area_ar: 'معبد سينجو', area_en: 'Sinnoh Temple', conditions_ar: 'بعد إكمال القصة', conditions_en: 'After completing the story', rarity: 'very_rare', is_alpha: false },
  { id: 'spawn-arceus-1', pokemon_id: 'arceus', location_id: 'coronet-highlands', area_ar: 'قمة كورونيت', area_en: 'Coronet Peak', conditions_ar: 'بعد إكمال كل شيء', conditions_en: 'After completing everything', rarity: 'very_rare', is_alpha: false },
];

export const seedMoves: Move[] = [
  { id: 'tackle', name_ar: 'صدم', name_en: 'Tackle', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 35, description_ar: 'يصدم الخصم بكامل جسمه.', description_en: 'A full-body charge attack.' },
  { id: 'ember', name_ar: 'جمرة', name_en: 'Ember', type: 'fire', category: 'special', power: 40, accuracy: 100, pp: 25, description_ar: 'يُطلق شرارات نارية صغيرة.', description_en: 'Attacks with small flames.' },
  { id: 'water-gun', name_ar: 'مسدس الماء', name_en: 'Water Gun', type: 'water', category: 'special', power: 40, accuracy: 100, pp: 25, description_ar: 'يُطلق نفث ماء قوي.', description_en: 'Squirts water at the target.' },
  { id: 'thunder-shock', name_ar: 'صدمة الرعد', name_en: 'Thunder Shock', type: 'electric', category: 'special', power: 40, accuracy: 100, pp: 30, description_ar: 'صدمة كهربائية قد تسبب الشلل.', description_en: 'An electric shock that may paralyze.' },
  { id: 'vine-whip', name_ar: 'سوط الكرمة', name_en: 'Vine Whip', type: 'grass', category: 'physical', power: 45, accuracy: 100, pp: 25, description_ar: 'يضرب بكروم رفيعة.', description_en: 'Strikes with thin vines.' },
  { id: 'psychic', name_ar: 'نفسي', name_en: 'Psychic', type: 'psychic', category: 'special', power: 90, accuracy: 100, pp: 10, description_ar: 'موجة نفسية قوية.', description_en: 'A strong psychic wave.' },
  { id: 'shadow-ball', name_ar: 'كرة الظل', name_en: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 15, description_ar: 'يُطلق كرة من الظلام.', description_en: 'Launches a shadowy blob.' },
  { id: 'rock-slide', name_ar: 'انهيار صخري', name_en: 'Rock Slide', type: 'rock', category: 'physical', power: 75, accuracy: 90, pp: 10, description_ar: 'يُسقط صخوراً على الخصم.', description_en: 'Drops rocks on the foe.' },
  { id: 'dragon-pulse', name_ar: 'نبضة التنين', name_en: 'Dragon Pulse', type: 'dragon', category: 'special', power: 85, accuracy: 100, pp: 10, description_ar: 'موجة طاقة تنينية.', description_en: 'A dragon energy wave.' },
  { id: 'flamethrower', name_ar: 'قاذف اللهب', name_en: 'Flamethrower', type: 'fire', category: 'special', power: 90, accuracy: 100, pp: 15, description_ar: 'يُطلق لهباً حارقاً.', description_en: 'Scorches the target with fire.' },
];

export const seedItems: Item[] = [
  { id: 'poke-ball', name_ar: 'كرة بوكي', name_en: 'Poké Ball', type: 'pokeball', description_ar: 'كرة لصيد البوكيمون.', description_en: 'A ball for catching Pokémon.' },
  { id: 'great-ball', name_ar: 'كرة عظيمة', name_en: 'Great Ball', type: 'pokeball', description_ar: 'كرة أفضل من الكرة العادية.', description_en: 'A better ball than a Poké Ball.' },
  { id: 'ultra-ball', name_ar: 'كرة فائقة', name_en: 'Ultra Ball', type: 'pokeball', description_ar: 'كرة ممتازة لصيد البوكيمون.', description_en: 'An excellent ball for catching.' },
  { id: 'potion', name_ar: 'جرعة', name_en: 'Potion', type: 'medicine', description_ar: 'تستعيد 20 نقطة صحة.', description_en: 'Restores 20 HP.' },
  { id: 'super-potion', name_ar: 'جرعة فائقة', name_en: 'Super Potion', type: 'medicine', description_ar: 'تستعيد 60 نقطة صحة.', description_en: 'Restores 60 HP.' },
  { id: 'oran-berry', name_ar: 'توت أوران', name_en: 'Oran Berry', type: 'berry', description_ar: 'توت يستعيد 10 صحة.', description_en: 'A berry that restores 10 HP.' },
  { id: 'fire-stone', name_ar: 'حجر النار', name_en: 'Fire Stone', type: 'evolution', description_ar: 'حجر يُطور بعض البوكيمونات.', description_en: 'Evolves certain Pokémon.' },
  { id: 'thunder-stone', name_ar: 'حجر الرعد', name_en: 'Thunder Stone', type: 'evolution', description_ar: 'حجر يُطور بعض البوكيمونات.', description_en: 'Evolves certain Pokémon.' },
  { id: 'water-stone', name_ar: 'حجر الماء', name_en: 'Water Stone', type: 'evolution', description_ar: 'حجر يُطور بعض البوكيمونات.', description_en: 'Evolves certain Pokémon.' },
  { id: 'black-tumblestone', name_ar: 'حجر أسود', name_en: 'Black Tumblestone', type: 'crafting', description_ar: 'مادة لصنع كرات الصيد.', description_en: 'Material for crafting balls.' },
];

export const seedRequests: Request[] = [
  {
    id: 'req-1',
    title_ar: 'البوكيمون الغامض في الليل',
    title_en: 'The Mysterious Night Pokémon',
    giver: 'Beauregard',
    location_id: 'obsidian-fieldlands',
    requirements_ar: 'أمسك دريفلون',
    requirements_en: 'Catch a Drifloon',
    steps_ar: '1. اذهب إلى غابة خشب القلب ليلاً\n2. ابحث عن دريفلون العائم\n3. أمسكه وأعده لبوريجارد',
    steps_en: '1. Go to Heartwood at night\n2. Look for the floating Drifloon\n3. Catch it and return to Beauregard',
    rewards_ar: '3x توت أوران + 1000 نقدة',
    rewards_en: '3x Oran Berry + 1000 coins',
  },
  {
    id: 'req-2',
    title_ar: 'تحدي الصخور',
    title_en: 'The Rock Challenge',
    giver: 'Anvin',
    location_id: 'crimson-mirelands',
    requirements_ar: 'هزم 3 جيودود',
    requirements_en: 'Defeat 3 Geodude',
    steps_ar: '1. اذهب إلى منحدر الصخور\n2. ابحث عن جيودود\n3. هزم 3 منهم في القتال',
    steps_en: '1. Go to Bolderoll Ravine\n2. Find Geodude\n3. Defeat 3 of them in battle',
    rewards_ar: '5x كرة عظيمة + 2000 نقدة',
    rewards_en: '5x Great Ball + 2000 coins',
  },
  {
    id: 'req-3',
    title_ar: 'البحث عن بيكاتشو',
    title_en: 'The Search for Pikachu',
    giver: 'Marli',
    location_id: 'obsidian-fieldlands',
    requirements_ar: 'أمسك بيكاتشو',
    requirements_en: 'Catch a Pikachu',
    steps_ar: '1. انتظر حتى تأتي عاصفة\n2. اذهب إلى طبيعة البرق\n3. ابحث عن بيكاتشو وأمسكه',
    steps_en: '1. Wait for a storm\n2. Go to Nature\'s Pantry\n3. Find and catch Pikachu',
    rewards_ar: '1x حجر الرعد + 3000 نقدة',
    rewards_en: '1x Thunder Stone + 3000 coins',
  },
];

export async function loadSeedData() {
  const { db } = await import('./db');
  
  // Check if already has data
  const count = await db.pokemon.count();
  if (count > 0) return;
  
  // Load seed data
  await Promise.all([
    db.pokemon.bulkAdd(seedPokemon),
    db.locations.bulkAdd(seedLocations),
    db.spawns.bulkAdd(seedSpawns),
    db.moves.bulkAdd(seedMoves),
    db.items.bulkAdd(seedItems),
    db.requests.bulkAdd(seedRequests),
  ]);
  
  console.log('Seed data loaded successfully!');
}